# [Different Ways to Create Numpy Arrays](https://www.pluralsight.com/guides/different-ways-create-numpy-arrays)

### Using Numpy functions

In [2]:
import numpy as np
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
arr.shape

(20,)

In [4]:
arr[3]

3

In [7]:
arr[-3]

17

#### Numpy Arrays are mutable

In [8]:
arr[3] = 100
arr

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

#### Unlike Python lists, the contents of a Numpy array are homogenous. 

In [11]:
arr[3] ='Numpy'
arr

ValueError: invalid literal for int() with base 10: 'Numpy'

### Creating a Two-dimensional Array

In [12]:
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [13]:
arr.shape

(4, 5)

In [21]:
arr[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [19]:
arr[2,2]

12

In [18]:
arr[-2, -2]

13

### Creating a Three-dimensional Array and Beyond

In [25]:
arr = np.arange(24).reshape(2,3,4)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
arr = np.arange(24).reshape(2,4,-1)

In [29]:
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]])

#### Also, using the arange function, you can create an array with a particular sequence between a defined start and end values

In [33]:
arr = np.arange(10, 35, 3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34])

### Using Other Numpy Functions

In [34]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
# The empty function creates an array. Its initial content is random and depends on the state of the memory.
np.empty((3,3))

array([[4.94e-323, 6.42e-323, 7.91e-323],
       [9.39e-323, 1.09e-322, 1.24e-322],
       [1.38e-322, 1.53e-322, 1.68e-322]])

In [38]:
# The full function creates a n * n array filled with the given value.
np.full((5,3),17)

array([[17, 17, 17],
       [17, 17, 17],
       [17, 17, 17],
       [17, 17, 17],
       [17, 17, 17]])

In [40]:
# The eye function lets you create a n * n matrix with the diagonal 1s and the others 0.
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.eye(4,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.]])

In [43]:
# The function linspace returns evenly spaced numbers over a specified interval.
np.linspace(0, 10, num=4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

## Conversion from Python Lists

In [44]:
np.array([[1,2,3,4]])

array([[1, 2, 3, 4]])

In [48]:
list = [4,5,6]
list

[4, 5, 6]

In [49]:
type(list)

list

In [50]:
array = np.array(list)
array

array([4, 5, 6])

In [51]:
type(array)

numpy.ndarray

#### To create a two-dimensional array, pass a sequence of lists to the array function.

In [61]:
arr = np.array([(1,2,3), (4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
arr.shape

(2, 3)

In [63]:
arr = np.array([(1,2,3), (4,5,6,7)])
arr

array([(1, 2, 3), (4, 5, 6, 7)], dtype=object)

In [64]:
arr.shape

(2,)

### Using Special Library Functions

To create an array filled with `random` values between 0 and 1, use random function. This is particularly useful for problems where you need a random state to get started.

In [69]:
np.random.random((2,2))

array([[0.17167653, 0.82488642],
       [0.07721907, 0.77089825]])

In [70]:
np.random.rand(2,2)

array([[0.20540515, 0.80944512],
       [0.64181537, 0.85888928]])

In [72]:
np.random.randn(2,2)

array([[-0.73660805, -0.39540998],
       [ 0.95902453,  1.36181666]])